### ISSUE TITLE
Append to output not working

### ISSUE THREAD

**Issue by guidobender** [nicolasbock/filechooser#239]
Hi Nick,
I am trying out Version: 1.3.3-25-g1a36cb4
When I select an empty existing folder, then the program aborts.
When I use an folder that doesn't exist, then it runs through.

Seems like the --append option disappeared that was earlier part in the program. Not sure if that was ever functional, but somehow if that functionality would be there, then that would be great.

**Comment by nicolasbock** [comment]
I moved the `--append` option into the `--destination-option`. Sorry, that might not have been super intuitive. So basically you now have to

```console
pick-files --destination-option append`
```

to get the same behavior. I will re-add the old options and mark them as deprecated so that you can still use the old way of calling the program.

**Comment by nicolasbock** [comment]
I added the old options back.
